[theme]
base = "light"
primaryColor = "#0e2a47ff"
backgroundColor ="#f0f4f8"
secondaryBackgroundColor = "#dbeafe"
textColor = "#374151"

[theme.sidebar]
primaryColor = "#0e2a47"
backgroundColor = "#0e2a47"
textColor = "#f5f6f8ff"
