[theme]
base = "light"
secondaryBackgroundColor = "#7fb8f5"   # <- 6-digit hex
textColor = "#111827"                  # dark text for light theme
codeFontSize = 16

[client]
toolbarMode = "developer"

[server]
headless = true
fileWatcherType = "none"
enableXsrfProtection = true
