[theme]
base = "light"
primaryColor = "#f2f4faff"
backgroundColor ="rgba(226, 244, 252, 1)"
secondaryBackgroundColor = "5fbde6ff"
# textColor =
# linkColor =
# linkUnderline = 
# codeBackgroundColor =


