[theme]
base="light"
secondaryBackgroundColor="#7fb8f5ff"
textColor = "#FFFFFF"
codeFontSize = 16
[client]
toolbarMode = "developer"
[server]
headless = true
fileWatcherType = "none"   # <- disable watchdog to avoid inotify limit
enableXsrfProtection = true
