[theme]
base = "light"
primaryColor = "#f2f4fa"  # Slightly cooler light tone
backgroundColor = "rgba(226, 244, 252, 1)"  # Soft pastel blue
secondaryBackgroundColor = "#5fbde6ff"  # Vibrant blue highlight
textColor = "#333333"  # Dark gray for readability
linkColor = "#007acc"  # Bright blue for links
linkUnderline = True  # Underline links for visual clarity
codeBackgroundColor = "#e0f7fa"  # Light cyan for code blocks


[theme.sidebar]
primaryColor = "#0e2a47"
backgroundColor = "#0e2a47"
textColor = "#f5f6f8ff"
codeFontSize = 16
